Repository Tecnativa/docker-duplicity, pull requests merged in 2020-05, with the labels that each got.

#27 Update duplicity and add CI/CD
  .github/workflows/automerge.yml
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  Dockerfile
  README.md
  hooks/build
  hooks/pre_build
  hooks/push
Labels: automerge, enhancement

#31 Don't try to push image if you're not a member
  .github/workflows/ci.yaml
Labels: bug

#32 [ADD] Support for Openstack V2+ api endpoints
  Dockerfile
Labels: enhancement
